/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorPrincipal;
import Controlador.Escritor;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import Modelo.Estudiantes;
/**
 *
 * @author Che
 */
public class Principal extends javax.swing.JFrame {

     Estudiantes estudiante;
    ControladorPrincipal principal;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        principal=new ControladorPrincipal(this);
        controladorBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo_JM = new javax.swing.JMenu();
        Salir_JI = new javax.swing.JMenuItem();
        Registro_JM = new javax.swing.JMenu();
        RegistroCurso_JI = new javax.swing.JMenuItem();
        RegistroEstudiante_JI = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Archivo_JM.setText("Archivo");

        Salir_JI.setText("Salir");
        Archivo_JM.add(Salir_JI);

        jMenuBar1.add(Archivo_JM);

        Registro_JM.setText("Registro");

        RegistroCurso_JI.setText("Registro Curso");
        Registro_JM.add(RegistroCurso_JI);

        RegistroEstudiante_JI.setText("Registro Estudiante");
        Registro_JM.add(RegistroEstudiante_JI);

        jMenuBar1.add(Registro_JM);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void  controladorBotones()
     {
         this.Salir_JI.addActionListener(principal);
         this.RegistroCurso_JI.addActionListener(principal);
         this.RegistroEstudiante_JI.addActionListener(principal);
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
        
         File file = new File("miArchivo.txt");
        if(!file.exists())
        {
            try
            {
                file.createNewFile();
                System.out.println("creado");
            }
            catch(IOException e) {e.printStackTrace();}
          
        }
       
         Escritor escritor = new Escritor();
         
        escritor.write_file("miArchivo.txt", "Escribiendo algo");
         
         
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo_JM;
    private javax.swing.JMenuItem RegistroCurso_JI;
    private javax.swing.JMenuItem RegistroEstudiante_JI;
    private javax.swing.JMenu Registro_JM;
    private javax.swing.JMenuItem Salir_JI;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
