/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorVentanaEstudiantes;
import Modelo.Estudiantes;
/**
 *
 * @author Che
 */
public class VentanaEstudiante extends javax.swing.JFrame {
    ControladorVentanaEstudiantes control;
    /**
     * Creates new form VentanaEstudiante
     */
   
    public VentanaEstudiante() {
        initComponents();
        
        control=new ControladorVentanaEstudiantes(this);
        eventoBotones();
        
    }
    
    public Estudiantes devolverInfoEs()
    {
        Estudiantes est=new Estudiantes();
       est.setNombre(this.Nombre_JT.getText());
       est.setCedula(this.Cedula_JT.getText());
       est.setCarnet(this.Carnet_JT.getText());
       
       return est;
    }

    public Estudiantes devolverEstudiante()
    {
        Estudiantes est=new Estudiantes();
        
        est.setNombre(Nombre_JT.getText());//lo que estoy diciendo es que el set le asigno lo que tiene el campo de texto
        est.setCedula(Cedula_JT.getText());
        return est;
    }
    
    public void mostrarEstudiante(Estudiantes estu)
    {
       this.Nombre_JT.setText(estu.getNombre());
       this.Cedula_JT.setText(estu.getCedula());
       
    }
    public String devolverCarnet(){
        {
            return this.Carnet_JT.getText();
        }
    }
    
    public void eventoBotones()
    {
              
         this.Buscar.addActionListener(control);
         this.Eliminar.addActionListener(control);
         this.Modificar.addActionListener(control);
         this.Agregar.addActionListener(control);
    }
    
     public void Limpiar()
     {
         this.Nombre_JT.setText("");
         this.Cedula_JT.setText("");
         this.Carnet_JT.setText("");
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre_JL = new javax.swing.JLabel();
        Cedula_JL = new javax.swing.JLabel();
        Nombre_JT = new javax.swing.JTextField();
        Cedula_JT = new javax.swing.JTextField();
        Carnet_JL = new javax.swing.JLabel();
        Carnet_JT = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();

        Nombre_JL.setText("Nombre");

        Cedula_JL.setText("Cedula");

        Cedula_JT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cedula_JTActionPerformed(evt);
            }
        });

        Carnet_JL.setText("Carnet");

        Buscar.setIcon(new javax.swing.ImageIcon("E:\\buscar.png")); // NOI18N
        Buscar.setText("Buscar");

        Modificar.setIcon(new javax.swing.ImageIcon("E:\\modificar.png")); // NOI18N
        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Eliminar.setIcon(new javax.swing.ImageIcon("E:\\eliminar.png")); // NOI18N
        Eliminar.setText("Eliminar");

        Agregar.setIcon(new javax.swing.ImageIcon("E:\\agregar.png")); // NOI18N
        Agregar.setText("Agregar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Cedula_JL)
                            .addComponent(Nombre_JL)
                            .addComponent(Carnet_JL))
                        .addGap(18, 74, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cedula_JT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre_JT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Carnet_JT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(Buscar)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Agregar)
                        .addGap(26, 26, 26)
                        .addComponent(Modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Eliminar)
                        .addGap(60, 60, 60))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Nombre_JL)
                    .addComponent(Nombre_JT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cedula_JT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cedula_JL))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Carnet_JT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Carnet_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Modificar)
                    .addComponent(Eliminar)
                    .addComponent(Agregar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cedula_JTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cedula_JTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cedula_JTActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarActionPerformed

     
    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel Carnet_JL;
    private javax.swing.JTextField Carnet_JT;
    private javax.swing.JLabel Cedula_JL;
    private javax.swing.JTextField Cedula_JT;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel Nombre_JL;
    private javax.swing.JTextField Nombre_JT;
    // End of variables declaration//GEN-END:variables

  
}
