/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorVentanaCurso;
import Modelo.Curso;
/**
 *
 * @author Che
 */
public class VentanaCurso extends javax.swing.JFrame {

    ControladorVentanaCurso control;
    /**
     * Creates new form VentanaCurso
     */
    public VentanaCurso() {
        initComponents();
        control=new ControladorVentanaCurso(this);
        manejadorBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    public void manejadorBotones()
    {
        this.Agregar.addActionListener(control);
        this.Consultar.addActionListener(control);
        this.Modificar.addActionListener(control);
        this.Eliminar.addActionListener(control);
        this.Asignar.addActionListener(control);
        
    }
    
    public Curso devolverInfoCurso()
    {
        Curso cur=new Curso();
        cur.setNombre(this.Nombre_JT.getText());
        cur.setSiglas(this.Siglas_JT.getText());
        cur.setCantCreditos(this.Creditos_JT.getText());
        
        return cur;
    }
    public Curso devolverCurso()
    {
        Curso cur=new Curso();
        
        //Acá no falta siglas ? no ese no y sí es sí jajajaja
        cur.setNombre(Nombre_JT.getText());
        cur.setCantCreditos(Creditos_JT.getText());
        
        return cur;
    }
    public void vacio()
    {
        this.Nombre_JT.setText("");
        this.Siglas_JT.setText("");
        this.Creditos_JT.setText("");
    }
    public void mostrarCurso(Curso cur)
    {
        this.Nombre_JT.setText(cur.getNombre());
        this.Creditos_JT.setText(cur.getCantCreditos());
    }
    
    public void limpiar()
    {
        this.Nombre_JT.setText("");
        this.Creditos_JT.setText("");
        this.Siglas_JT.setText("");
     }
    
    public String devolverSiglas()
    {
        return this.Siglas_JT.getText();
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre_JL = new javax.swing.JLabel();
        Siglas_JL = new javax.swing.JLabel();
        Creditos_JL = new javax.swing.JLabel();
        Nombre_JT = new javax.swing.JTextField();
        Siglas_JT = new javax.swing.JTextField();
        Creditos_JT = new javax.swing.JTextField();
        Modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Asignar = new javax.swing.JButton();
        Consultar = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();

        Nombre_JL.setText("Nombre del Curso");

        Siglas_JL.setText("Siglas");

        Creditos_JL.setText("Creditos");

        Modificar.setIcon(new javax.swing.ImageIcon("E:\\modificar.png")); // NOI18N
        Modificar.setText("Modificar");

        Eliminar.setIcon(new javax.swing.ImageIcon("E:\\eliminar.png")); // NOI18N
        Eliminar.setText("Eliminar");

        Asignar.setText("Asignar");

        Consultar.setText("Consultar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });

        Agregar.setIcon(new javax.swing.ImageIcon("E:\\Agregar.png")); // NOI18N
        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(Asignar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre_JL)
                            .addComponent(Siglas_JL)
                            .addComponent(Creditos_JL))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Creditos_JT, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(Siglas_JT)
                            .addComponent(Nombre_JT))
                        .addGap(35, 35, 35)
                        .addComponent(Consultar)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_JL)
                    .addComponent(Nombre_JT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Siglas_JL)
                    .addComponent(Siglas_JT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Consultar))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Creditos_JL)
                    .addComponent(Creditos_JT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Agregar)
                            .addComponent(Modificar))
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Eliminar)
                            .addComponent(Asignar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Asignar;
    private javax.swing.JButton Consultar;
    private javax.swing.JLabel Creditos_JL;
    private javax.swing.JTextField Creditos_JT;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel Nombre_JL;
    private javax.swing.JTextField Nombre_JT;
    private javax.swing.JLabel Siglas_JL;
    private javax.swing.JTextField Siglas_JT;
    // End of variables declaration//GEN-END:variables
}
